services:
#    vente.example:
#        class: VenteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

      vente.twig_extension:
          class: VenteBundle\Twig\VenteExtension
          tags:
            - { name : twig.extension }
